[program:vpp_promisc.sh]
command=/usr/local/bin/vpp_promisc.sh
priority=2
autostart=false
autorestart=unexpected
startsecs=5
stdout_logfile=syslog
stderr_logfile=syslog
dependent_startup=true
dependent_startup_wait_for=vpp_init.sh:running
