# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

parameters:
  - name: debian_version
    type: string
    default: trixie
  - name: arch
    type: string
    default: amd64

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: BuildVpp

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      debian_version: ${{ parameters.debian_version }}
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      debian_version: bookworm
