FROM debian:bookworm

ARG docker_container_name

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

ARG user
ARG uid
ARG guid

RUN mkdir /app
COPY /run_build.sh /run_build.sh
RUN chmod +x /run_build.sh
{% for pkg in VPP_DOCKER_DEBS.split() %}
COPY /debs/{{ pkg }} /app
{% endfor %} 
RUN apt-get update 

RUN apt-get install -f -y make curl sudo git

{% for pkg in VPP_DOCKER_DEBS.split() %}
RUN dpkg -i /app/{{ pkg }} || apt-get install -f -y
{% endfor %}

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /app

ENV USER $user

RUN groupadd -f -r -g $guid g$user

RUN useradd $user -l -u $uid -g $guid -d /var/$user -m -s /bin/bash

# Config git for stg
RUN su $user -c "git config --global user.name $user"
RUN su $user -c "git config --global user.email $user@contoso.com"

#RUN chown $user /var/$user/.ssh -R
#RUN chmod go= /var/$user/.ssh -R

# Add user to sudoers
RUN echo "$user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers

USER $user

